# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Development and Programming | Álvaro González Álvarez
email: alvaro@alvarogonzalezalvarez.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Álvaro González Álvarez and this is my Web Development Blog. Let's talk about Programming, Web Technologies, Java, JavaScript and WebSphere Commerce
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://alvarogonzalezalvarez.com" # the base hostname & protocol for your site
twitter_username: alvaro_gzz
github_username:  alvarogonzalezalvarez

# Build settings
markdown: kramdown
permalink: /:seo/:title/
